changelog:
  exclude:
    labels:
      - ignore-for-releases
  categories:
    - title: Added
      labels:
        - "*"
      exclude-labels:
        - bug
        - refactoring
    - title: Changed
      labels:
        - refactoring
    #- title: Deprecated
    #- title: Removed
    - title: Fixed
      labels:
        - bug
    #- title: Security
    #  labels:
