name: Run Tests on Pull Requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen #node v18 LTS
          check-latest: true
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM Clean Install
        run: npm ci
      - name: Test The Release With Defaults (Reference-Components & Reference-Theme)
        run: npm test
      - name: Test The Release With Expanse and Components
        env:
          GITHUB_ID: ${{ secrets.PERSONAL_ACCESS_ID }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          COMPONENTS_REPO: "https://github.com/archetype-themes/components.git"
          THEME_REPO: "https://github.com/archetype-themes/expanse.git"
        run: npm test
