name: Run Tests on Pull Requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_ID: ${{ secrets.PERSONAL_ACCESS_ID }}
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      NODE_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen #node v18 LTS
          check-latest: true
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM Clean Install
        run: npm ci
      - name: Test The Release
        run: npm test
