name: Run Tests on Pull Requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: archetype-themes/workflows/.github/workflows/npm-test-and-lint.yml@main
