name: Run Tests on Pull Requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      # Install dependencies
      - run: npm ci
      # Run tests
      - run: npm test
      # Run Circular Dependencies Check
      - run: npm run cdc
      # Run lint check
      - run: npm run lint
